version: '3'

services:

  server1:
    build: ./server1
    container_name: server1
    restart: unless-stopped
    ports:
      - "3001:3001"
  
  server2:
    build: ./server2
    container_name: server2
    restart: unless-stopped
    ports:
      - "3002:3002"
  
  server3:
    build: ./server3
    container_name: server3
    restart: unless-stopped
    ports:
      - "2999:2999"
  
  client:
    build: ../kr-client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server1
      - server2
      - server3

